# Generated by Django 4.0.4 on 2022-05-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
