# Generated by Django 4.0.4 on 2022-05-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_city_alter_event_description_alter_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='weather',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
