# Generated by Django 4.0.4 on 2022-05-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_event_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='weather',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
