# Generated by Django 4.0.4 on 2022-05-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('globalName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('organizer', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
