# Generated by Django 4.0.4 on 2022-05-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_globalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalevent',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
