# Generated by Django 4.0.4 on 2022-05-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_globalevent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalevent',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
