# Generated by Django 4.0.4 on 2022-05-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_globalevent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalevent',
            old_name='globalName',
            new_name='name',
        ),
    ]
