# Generated by Django 4.0.4 on 2022-05-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_globalname_globalevent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
